sudo: true

language: node_js

node_js:
  - "4"
  - "6"

before_install:
  # Install build tools needed for some NPM packages
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 g++-4.8 -y

before_script:
  - "mysql -u root -e 'create database actionhero_test'"

os:
  - linux

script: npm run test

services:
  - redis-server
  - mysql
  - postgresql
